parser: '@typescript-eslint/parser'
parserOptions:
  project : './tsconfig.json'
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
env:
  jest: true
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
rules:
  react/prop-types: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': error
settings:
  react:
    version: detect