parser: '@typescript-eslint/parser'
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
extends:
  - standard
  - standard-react
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
rules:
  react/prop-types: 0
  # react-hooks/rules-of-hooks": error
  # react-hooks/exhaustive-deps": warn
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': error
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true